parameters:
    memcache.doctrine_cache.class: Lsw\MemcacheBundle\Doctrine\Cache\MemcacheCache
    memcache.session_handler.class: Lsw\MemcacheBundle\Session\Storage\LockingSessionHandler
    memcache.firewall_handler.class: Lsw\MemcacheBundle\Firewall\FirewallHandler

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Lsw\MemcacheBundle\Command\ClearCommand:
        calls:
            - [ setContainer, [ '@service_container'] ]

    Lsw\MemcacheBundle\Command\StatisticsCommand:
        calls:
            - [ setContainer, [ '@service_container'] ]
