parameters:
    memcache.data_collector.class: Lsw\MemcacheBundle\DataCollector\MemcacheDataCollector
    memcache.data_collector.template: "Collector/memcache.html.twig"

services:
    memcache.data_collector:
        class: "%memcache.data_collector.class%"
        tags:
            - { name: data_collector, template: "%memcache.data_collector.template%", id: "memcache" }
